### PR TITLE
`DateValidator`s & `List<EveryDateValidator>`

### PR DESCRIPTION
**Pull request by FMorschel**
Here its my first draft for a new feature. With the new `DateValidator` class being implemented by the `Every`s created by this package, we now can do the following:

```dart
const mondays = EveryWeekday(Weekday.monday);
const tuesdays = EveryWeekday(Weekday.tuesday);
const list = [mondays, tuesdays];
final startDate2 = DateTime(2022, DateTime.january, 1);
DueDateTime date = DueDateTime.fromDate(
  startDate2,
  EveryDateValidatorUnion(list),
);
for (; date.isBefore(january31st); date = date.next) {
  print(date.toString()); // January: 3, 4, 10, 11, 17, 18, 24, 25, 31 
}
```

There are only a few tests that stopped working, but those actually *should* stop working. And the changes made for the `Every`s implemented by this package were necessary for the lists to be able to add and subtract days the right way.

Any suggestions are welcome.

### CODE REVIEW

**Comment by FMorschel** [comment]
I do have a question that I wanted to ask, If you think about it, both `Intersection` and `Difference` lists have a little problem where they can continue processing forever. The thing that I wanted to ask was do you think I ask for a `Duration`, or a `DateTime` limit on them? And then, what do you think should be the default if we ask for a Duration? Since the DateTime can't have a default value because it can't be constant.

**Comment by fecaletti** [comment]
In my opinion, the best and simpler option would be use a DateTime as an argument in both cases. So you would force the user to insert a meaningful limit in the context of his implementation, as it would not be possible to set a default value, and you can simply use it inside your loop. Also, by using DateTime, it is easier to consider timezone specifications, like daylight.

**Comment by FMorschel** [comment]
My point here would be then, how would we set this up on the actual `DueDateTime` class when we use the `next` getter? Not giving anything? on the `addSomeTime` methods, like `addWeeks` and such, do you think adding a new parameter is the best approach? What do we do with it if the `Every` isn't a `LimitedEvery`?

**Comment by FMorschel** [comment]
I've decided on that. I'm going to make a breaking change to the API. And define a rule forward. 

I'm exchanging all optional parameters for named parameters and making the getters for `next` and `previous` on `DueDateTime` become methods with an optional named parameter for the `DateTime? limit` that will be ignored if the expression `every is LimitedEvery` returns `false`.

**Comment by FMorschel** [comment]
I'll leave this open for a few days to think about it and receive suggestions of any kind. Maybe some more test suggestions?

**Pull request merged**
